### ISSUE TITLE
Missing button

### ISSUE THREAD

**Issue by yuyanchua** [adrianaregalado/Pawfinder#48]
**Summary**
Missing confirm button in the filter page
**Description**
There should be a confirm button to confirm the choice of the filter in the pet filter page
**Severity**
Critical
**Suggestion**
Implement a confirm button for the filter page

**Comment by adrianaregalado** [comment]
The filter page has been updated, but we have chosen not to implement a button. Simply clicking the back arrow at the top will apply the filter.
